name: "🐛 Bug Report"
description: Create a new ticket for a bug.
title: "🐛 [BUG] - <title>"
labels: [
  "bug"
]
body:
  - type: input
    id: affects
    attributes:
      label: Where is the bug?
      description: Class, interface, function, etc. containing the bug
      placeholder: Please be as specific as you can...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: What did you expect to happen?

  - type: textarea
    id: actual-behavior
    attributes:
      label: "Actual Behavior"
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to reproduce"
      description: Please enter an explicit description of your issue
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
      
  - type: input
    id: php-version
    attributes:
      label: "PHP Version"
      description: What version of PHP are you using?
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: "Environment"
      description: What's your environment? (I.e., OS, web server, anything else that might be useful)
    validations:
      required: false
